name: Build release ZIP

on:
  release:
    types: [published]

jobs:
  build:
    name: Build module ZIP
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create module ZIP
        run: zip "GMSTrashDisabler-${{ github.ref_name }}.zip" customize.sh module.prop gmslist.txt

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./GMSTrashDisabler-${{ github.ref_name }}.zip
          asset_name: GMSTrashDisabler-${{ github.ref_name }}.zip
          asset_content_type: application/zip

